[package]
name = "piece_table_rs"
version = "0.1.3"
edition = "2021"
authors = ["linket <t.linke@pripares.com>"]
description = "piece table data structure"
license = "MIT"
repository = "https://github.com/LinkeTh/piece_table"

[dependencies]
